services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
      POSTGRES_ADMIN_PASSWORD: dev-admin-password
      POSTGRES_DB: sociable
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
